name = "gleam_otp"
version = "0.6.0"
licences = ["Apache-2.0"]
description = "Fault tolerant multicore Gleam programs with OTP"

gleam = ">= 0.30.0"

repository = { type = "github", user = "gleam-lang", repo = "otp" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_erlang = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.5"
